// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: sns.proto

package sns

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SocialMediaService_CreatePost_FullMethodName     = "/sns.SocialMediaService/CreatePost"
	SocialMediaService_GetPostById_FullMethodName    = "/sns.SocialMediaService/GetPostById"
	SocialMediaService_UpdatePost_FullMethodName     = "/sns.SocialMediaService/UpdatePost"
	SocialMediaService_DeletePost_FullMethodName     = "/sns.SocialMediaService/DeletePost"
	SocialMediaService_CreateComment_FullMethodName  = "/sns.SocialMediaService/CreateComment"
	SocialMediaService_GetCommentById_FullMethodName = "/sns.SocialMediaService/GetCommentById"
	SocialMediaService_UpdateComment_FullMethodName  = "/sns.SocialMediaService/UpdateComment"
	SocialMediaService_DeleteComment_FullMethodName  = "/sns.SocialMediaService/DeleteComment"
	SocialMediaService_CreateLike_FullMethodName     = "/sns.SocialMediaService/CreateLike"
	SocialMediaService_GetLikeById_FullMethodName    = "/sns.SocialMediaService/GetLikeById"
	SocialMediaService_UpdateLike_FullMethodName     = "/sns.SocialMediaService/UpdateLike"
	SocialMediaService_DeleteLike_FullMethodName     = "/sns.SocialMediaService/DeleteLike"
)

// SocialMediaServiceClient is the client API for SocialMediaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SocialMediaServiceClient interface {
	CreatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Post, error)
	GetPostById(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Post, error)
	UpdatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Post, error)
	DeletePost(ctx context.Context, in *ID, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*Comment, error)
	GetCommentById(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Comment, error)
	UpdateComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*Comment, error)
	DeleteComment(ctx context.Context, in *ID, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreateLike(ctx context.Context, in *Like, opts ...grpc.CallOption) (*Like, error)
	GetLikeById(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Like, error)
	UpdateLike(ctx context.Context, in *Like, opts ...grpc.CallOption) (*Like, error)
	DeleteLike(ctx context.Context, in *ID, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type socialMediaServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSocialMediaServiceClient(cc grpc.ClientConnInterface) SocialMediaServiceClient {
	return &socialMediaServiceClient{cc}
}

func (c *socialMediaServiceClient) CreatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, SocialMediaService_CreatePost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialMediaServiceClient) GetPostById(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, SocialMediaService_GetPostById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialMediaServiceClient) UpdatePost(ctx context.Context, in *Post, opts ...grpc.CallOption) (*Post, error) {
	out := new(Post)
	err := c.cc.Invoke(ctx, SocialMediaService_UpdatePost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialMediaServiceClient) DeletePost(ctx context.Context, in *ID, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SocialMediaService_DeletePost_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialMediaServiceClient) CreateComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, SocialMediaService_CreateComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialMediaServiceClient) GetCommentById(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, SocialMediaService_GetCommentById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialMediaServiceClient) UpdateComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, SocialMediaService_UpdateComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialMediaServiceClient) DeleteComment(ctx context.Context, in *ID, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SocialMediaService_DeleteComment_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialMediaServiceClient) CreateLike(ctx context.Context, in *Like, opts ...grpc.CallOption) (*Like, error) {
	out := new(Like)
	err := c.cc.Invoke(ctx, SocialMediaService_CreateLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialMediaServiceClient) GetLikeById(ctx context.Context, in *ID, opts ...grpc.CallOption) (*Like, error) {
	out := new(Like)
	err := c.cc.Invoke(ctx, SocialMediaService_GetLikeById_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialMediaServiceClient) UpdateLike(ctx context.Context, in *Like, opts ...grpc.CallOption) (*Like, error) {
	out := new(Like)
	err := c.cc.Invoke(ctx, SocialMediaService_UpdateLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *socialMediaServiceClient) DeleteLike(ctx context.Context, in *ID, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, SocialMediaService_DeleteLike_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SocialMediaServiceServer is the server API for SocialMediaService service.
// All implementations must embed UnimplementedSocialMediaServiceServer
// for forward compatibility
type SocialMediaServiceServer interface {
	CreatePost(context.Context, *Post) (*Post, error)
	GetPostById(context.Context, *ID) (*Post, error)
	UpdatePost(context.Context, *Post) (*Post, error)
	DeletePost(context.Context, *ID) (*emptypb.Empty, error)
	CreateComment(context.Context, *Comment) (*Comment, error)
	GetCommentById(context.Context, *ID) (*Comment, error)
	UpdateComment(context.Context, *Comment) (*Comment, error)
	DeleteComment(context.Context, *ID) (*emptypb.Empty, error)
	CreateLike(context.Context, *Like) (*Like, error)
	GetLikeById(context.Context, *ID) (*Like, error)
	UpdateLike(context.Context, *Like) (*Like, error)
	DeleteLike(context.Context, *ID) (*emptypb.Empty, error)
	mustEmbedUnimplementedSocialMediaServiceServer()
}

// UnimplementedSocialMediaServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSocialMediaServiceServer struct {
}

func (UnimplementedSocialMediaServiceServer) CreatePost(context.Context, *Post) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (UnimplementedSocialMediaServiceServer) GetPostById(context.Context, *ID) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostById not implemented")
}
func (UnimplementedSocialMediaServiceServer) UpdatePost(context.Context, *Post) (*Post, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePost not implemented")
}
func (UnimplementedSocialMediaServiceServer) DeletePost(context.Context, *ID) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePost not implemented")
}
func (UnimplementedSocialMediaServiceServer) CreateComment(context.Context, *Comment) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedSocialMediaServiceServer) GetCommentById(context.Context, *ID) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentById not implemented")
}
func (UnimplementedSocialMediaServiceServer) UpdateComment(context.Context, *Comment) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedSocialMediaServiceServer) DeleteComment(context.Context, *ID) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedSocialMediaServiceServer) CreateLike(context.Context, *Like) (*Like, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLike not implemented")
}
func (UnimplementedSocialMediaServiceServer) GetLikeById(context.Context, *ID) (*Like, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLikeById not implemented")
}
func (UnimplementedSocialMediaServiceServer) UpdateLike(context.Context, *Like) (*Like, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLike not implemented")
}
func (UnimplementedSocialMediaServiceServer) DeleteLike(context.Context, *ID) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLike not implemented")
}
func (UnimplementedSocialMediaServiceServer) mustEmbedUnimplementedSocialMediaServiceServer() {}

// UnsafeSocialMediaServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SocialMediaServiceServer will
// result in compilation errors.
type UnsafeSocialMediaServiceServer interface {
	mustEmbedUnimplementedSocialMediaServiceServer()
}

func RegisterSocialMediaServiceServer(s grpc.ServiceRegistrar, srv SocialMediaServiceServer) {
	s.RegisterService(&SocialMediaService_ServiceDesc, srv)
}

func _SocialMediaService_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaServiceServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaService_CreatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaServiceServer).CreatePost(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialMediaService_GetPostById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaServiceServer).GetPostById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaService_GetPostById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaServiceServer).GetPostById(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialMediaService_UpdatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Post)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaServiceServer).UpdatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaService_UpdatePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaServiceServer).UpdatePost(ctx, req.(*Post))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialMediaService_DeletePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaServiceServer).DeletePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaService_DeletePost_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaServiceServer).DeletePost(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialMediaService_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Comment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaServiceServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaService_CreateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaServiceServer).CreateComment(ctx, req.(*Comment))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialMediaService_GetCommentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaServiceServer).GetCommentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaService_GetCommentById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaServiceServer).GetCommentById(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialMediaService_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Comment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaServiceServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaService_UpdateComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaServiceServer).UpdateComment(ctx, req.(*Comment))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialMediaService_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaServiceServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaService_DeleteComment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaServiceServer).DeleteComment(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialMediaService_CreateLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Like)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaServiceServer).CreateLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaService_CreateLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaServiceServer).CreateLike(ctx, req.(*Like))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialMediaService_GetLikeById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaServiceServer).GetLikeById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaService_GetLikeById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaServiceServer).GetLikeById(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialMediaService_UpdateLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Like)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaServiceServer).UpdateLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaService_UpdateLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaServiceServer).UpdateLike(ctx, req.(*Like))
	}
	return interceptor(ctx, in, info, handler)
}

func _SocialMediaService_DeleteLike_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SocialMediaServiceServer).DeleteLike(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SocialMediaService_DeleteLike_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SocialMediaServiceServer).DeleteLike(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

// SocialMediaService_ServiceDesc is the grpc.ServiceDesc for SocialMediaService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SocialMediaService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sns.SocialMediaService",
	HandlerType: (*SocialMediaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePost",
			Handler:    _SocialMediaService_CreatePost_Handler,
		},
		{
			MethodName: "GetPostById",
			Handler:    _SocialMediaService_GetPostById_Handler,
		},
		{
			MethodName: "UpdatePost",
			Handler:    _SocialMediaService_UpdatePost_Handler,
		},
		{
			MethodName: "DeletePost",
			Handler:    _SocialMediaService_DeletePost_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _SocialMediaService_CreateComment_Handler,
		},
		{
			MethodName: "GetCommentById",
			Handler:    _SocialMediaService_GetCommentById_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _SocialMediaService_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _SocialMediaService_DeleteComment_Handler,
		},
		{
			MethodName: "CreateLike",
			Handler:    _SocialMediaService_CreateLike_Handler,
		},
		{
			MethodName: "GetLikeById",
			Handler:    _SocialMediaService_GetLikeById_Handler,
		},
		{
			MethodName: "UpdateLike",
			Handler:    _SocialMediaService_UpdateLike_Handler,
		},
		{
			MethodName: "DeleteLike",
			Handler:    _SocialMediaService_DeleteLike_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sns.proto",
}
